### ISSUE TITLE
Upload image to docker hub

### ISSUE THREAD

**Issue by thomas15v** [BirkhoffLee/NamelessMC-docker#3]
Well title kinda says it 😄.

It is fairly easy to setup an automated build with docker hub.

Than you only have to beg the official creators for a git hook so you can automatically update the image when they make changes to it.

(Also the account for NamelessMC isn't claimed on docker hub yet, but you might wanna discuss that with the official creators as well.)

**Comment by BirkhoffLee** [comment]
Yeah I forgot to create one :p
I'll do that later, thanks for noticing!

**Comment by birkhofflee** [comment]
Well the auto update might be a little more complicated, I'll look into it later.

**Comment by birkhofflee** [comment]
https://github.com/NamelessMC/Nameless/issues/642
